// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SAN_ParallaxPicture","status":true,"description":"パララックスピクチャ ver1.0.2\r\nピクチャを遠景風にスクロール表示します。","parameters":{}}
];
